home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='index'),
    path('stream', views.stream, name='stream'),
]

manager/urls.py
from django.urls import path
from . import views
from manager.views import (
    PostpayListView, 
    EditionListView,
    PostpayUpdateView,
    EditionCreateView,
    EditionUpdateView,
    PostnotpayListView,
    PostListView,
    UserListView,
    UserUpdateView,
    UserPostListView,
    PostUpdateView,
    CustomListView,
    CustomUpdateView
)
from account.views import PostDeleteView, PostPayDeleteView

urlpatterns = [
    path('manager_home',PostpayListView.as_view(), name='manager-home'),
    path('postpay/<int:pk>/',PostpayUpdateView.as_view(),name='postpay-detail'),
    path('edition/create',EditionCreateView.as_view(), name='edit-create'),
    path('edition/',EditionListView.as_view(), name='edit-list'),
    path('edition/update/<int:pk>/',EditionUpdateView.as_view(), name='edit-update'),
    path('postpay/notpay',PostnotpayListView.as_view(), name='notpay-list'),
    path('post',PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostUpdateView.as_view(), name='post-detail'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('postpay/<int:pk>/delete',
         PostPayDeleteView.as_view(), name='postpay-delete'),
    path('user_list',UserListView.as_view(), name='user-list'),
    path('user_detail/<int:pk>/',UserUpdateView.as_view(), name='user-detail'),
    path('user_post/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('custom',CustomListView.as_view(), name='custom-list'),
    path('custom/<int:pk>/',CustomUpdateView.as_view(),name='custom-update'),
]

sign/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from sign import view
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include(('home.urls', 'home'), namespace='home')),
    path('user/', include(('account.urls', 'account'), namespace='account')),
    path('manager/', include(('manager.urls', 'manager'), namespace='manager')),
    path('register/', view.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
] + static(settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

manager/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Edition(models.Model):
    edit_name = models.CharField(max_length=100)
    edit_img = models.ImageField(upload_to='edition_img', blank=True)
    charge = models.IntegerField()

    def __str__(self):
        return self.edit_name

    def save(self, *args, **kwargs):
        super().save()
    
    def get_absolute_url(self):
        return reverse("manager:edit-list")

class User(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        super().save()
    
    def get_absolute_url(self):
        return reverse("manager:user-list")



    

manager/forms.py
from django import forms
from django.contrib.auth.models import User
from account.models import PostPay, Post


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    first_name = forms.CharField(label='User name')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']


class PostPayUpdateForm(forms.ModelForm):
    paid = forms.BooleanField(required=False, label='完成繳費')

    class Meta:
        model = PostPay
        fields = ['paid']


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

home/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from account.models import Post

# Create your views here.


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'index.html', context)

def stream(request):
    return render(request, 'live_streaming.html')

manager/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.models import User
from .models import Edition
from account.models import Post, PostPay, Profile, Customized
from django.http import HttpResponseRedirect, request
from django.views.generic import (View, ListView,DetailView,CreateView, UpdateView, DeleteView)
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import UserUpdateForm , PostPayUpdateForm
from django.contrib import messages
from django.urls import reverse
# from manager.forms import PostpayUpdateForm
# from django.contrib import messages

def home(request):
    context = {
        'pays': PostPay.objects.all()
    }
    return render(request,'manager/home.html',context)

def edition_list(request):
    context = {
        'editions':Edition.objects.all()
    }
    return render(request, 'manager/edition_list.html', context)

def post_list(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'manager/post_list.html', context)

def user_list(request):
    context = {
        'users': User.objects.all()
    }
    return render(request, 'manager/user_list.html', context)

def custom(request):
    context = {
        'customs': Customized.objects.all()
    }
    return render(request, 'manager/custom_list.html', context)

class EditionListView(ListView):
    model = Edition
    context_object_name='editions'
    template_name = 'manager/edition_list.html'
    paginate_by = 10

class EditionCreateView(LoginRequiredMixin, CreateView):
    model = Edition
    fields = ['edit_name', 'edit_img', 'charge']
    template_name = 'manager/edition_create.html'

    def form_vaild(self, form):
        self.object = form.save()
        return super.form_vaild(form)


class EditionUpdateView(LoginRequiredMixin, UpdateView):
    model = Edition
    fields = ['edit_name', 'edit_img', 'charge']
    template_name = 'manager/edition_update.html'

    def form_vaild(self, form):
        return super.form_vaild(form)

class PostpayListView(ListView):
    model = PostPay
    template_name = 'manager/home.html'
    context_object_name='pays'
    ordering = ['paid']
    paginate_by = 10

class PostnotpayListView(ListView):
    model = PostPay
    template_name = 'manager/notpay_list.html'
    context_object_name='pays'
    paginate_by = 10

class PostpayUpdateView(LoginRequiredMixin, UpdateView):
    model = PostPay
    form_class = PostPayUpdateForm
    # fields = [ 'paid' ]
    template_name = 'manager/postpay_detail.html'

    def form_vaild(self, form):
        return super.form_vaild(form)

    def get_success_url(self):
        return reverse('manager:notpay-list')

class PostListView(ListView):
    model = Post
    template_name = 'manager/post_list.html'
    context_object_name='posts'
    ordering = ['date_post']
    paginate_by = 10

class PostUpdateView(UpdateView):
    model = Post
    fields = ['title',
              'date_post',
              'edition',
              'video_url',
              'mar_text',
              'image',
              'content',
              'qrcode'
              ]
    template_name = 'manager/post_detail.html'

    def form_vaild(self, form):
        return super.form_vaild(form)

    def get_success_url(self):
        return reverse('manager:post-list')

class UserListView(ListView):
    model = User
    template_name = 'manager/user_list.html'
    context_object_name='users'
    paginate_by = 10

class UserUpdateView(UpdateView):
    model = User
    fields = [ 'username', 'first_name', 'email' ]
    template_name = 'manager/user_detail.html'

    def form_vaild(self, form):
        return super.form_vaild(form)

    def get_success_url(self):
        user_id = self.kwargs['pk']
        return reverse('manager:user-detail', kwargs={'pk':user_id})

class UserPostListView(ListView):
    model = Post
    template_name = 'manager/user_posts.html'
    context_object_name='posts'
    paginate_by = 10

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('date_post')
    
    def get_success_url(self):
        username = self.kwargs['username']
        return reverse('user-posts', kwargs={'username': username})

class CustomUpdateView(LoginRequiredMixin, UpdateView):
    model = Customized
    fields = [ 'contact', 'field', 'date', 'charge', 'note' ]
    template_name = 'manager/custom_update.html'

    def form_vaild(self, form):
        return super.form_vaild(form)

    def get_success_url(self):
        return reverse('manager:custom-list')

class CustomListView(ListView):
    model = Customized
    template_name = 'manager/custom_list.html'
    context_object_name='customs'
    paginate_by = 10

manager/templates/manager/base.html
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% if title %}
        <title>{{ user.username }}-{{ title }}</title>
    {% else %}
        <title>Manager Home</title>
    {% endif %}
    <!-- VUE -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.9/vue.js"></script>
    
    <!-- MUSE-UI CSS -->
    <link rel="stylesheet" href="https://unpkg.com/muse-ui/dist/muse-ui.css">
    <script src="https://unpkg.com/muse-ui/dist/muse-ui.js"></script>
    <link rel="stylesheet" href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.css">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'account/main.css' %}">
  </head>
  <body style="background-color: #678F8D">
  
    <header>
      <nav style="background-color: #285059" class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'manager:manager-home' %}">ManagerHome</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'manager:edit-list' %}">版型</a>
                <a class="nav-item nav-link" href="{% url 'manager:notpay-list' %}">未付款</a>
                <a class="nav-item nav-link" href="{% url 'manager:post-list' %}">Post</a>
                <a class="nav-item nav-link" href="{% url 'manager:user-list' %}">使用者</a>
                <a class="nav-item nav-link" href="{% url 'manager:custom-list' %}">客製化</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">登出</a>
                {% if request.user.is_superuser  %}
                  <a class="nav-item nav-link" href="{% url 'register' %}">註冊</a>
                {% endif %}
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">登入</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <div class="push_top"></div>
    <main role="main" class="container">
      <div class="container">
        <div>
          {% if messages %}
            {% for messages in messages %}
              <div class="alert alert-{{ messages.tags }}">
                {{ messages }}
              </div>
            {% endfor %}
          {% endif %}
        </div>
        <div class="row">
          <div class="col-md-12">
            {% block content %}
            {% endblock content%}
          </div>
        </div>
      </div>
      <br>
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {% if is_paginated %}
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page=1">First</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
              </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                  </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                  </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number}}">Next</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
              </li>
            {% endif %}
          {% endif %}
        </ul>
      </nav>
    </main>
    <script>
      new Vue().$mount('#button')
    </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

manager/templates/manager/custom_list.html
{% extends "manager/base.html" %}
{% block content %}
    <div class="form">
        <div>
            <h1 class="mb-3">客製化需求列表 ({{ page_obj.paginator.count }})</h1>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">聯絡人</th>
                    <th scope="col">所需欄位</th>
                    <th scope="col">上架時間</th>
                    <th scope="col">金額</th>
                    <th scope="col">備註</th>
                    <th scope="col">Update</th>
                </tr>
            </thead>
            {% for custom in customs %}
                <tr>
                <th>{{ forloop.counter }}</th>
                <td>{{ custom.contact }}</td>
                <td>{{ custom.field }}</td>
                <td>{{ custom.date }}</td>
                <td>{{ custom.charge }}</td>
                <td>{{ custom.note }}</td>
                <td><a href="{% url 'manager:custom-update' custom.id %}">update</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}

manager/templates/manager/custom_update.html
{% extends "manager/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div id="button" >
    <mu-button color="teal900" href="{% url 'manager:custom-list' %}">
        <mu-icon value="arrow_back" left></mu-icon>返回
    </mu-button>

    <article class="media content-section form">
        <div class="media-body">
            <p class="article-content">
                聯絡人：{{ object.contact }}
                所需欄位：{{ object.field }}
                上架時間：{{ object.date }}
                價格：{{ object.charge }}
                備註：{{ object.note }}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form|crispy }}
                    </fieldset>
                    <div style="margin-left: 40%;">
                        <mu-button type="submit" color="blue300" >
                            <mu-icon value="create" left></mu-icon>修改
                        </mu-button>
                    </div>
                </form>
            </p>
        </div>
    </article>
</div>
{% endblock content %}

manager/templates/manager/edition_create.html
{% extends "manager/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="form" id="button" >
    <mu-button color="teal900" href="{% url 'manager:edit-list' %}">
         <mu-icon value="arrow_back" left></mu-icon>返回
    </mu-button> 
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Edition</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                    <div style="margin-left: 40%;">
                        <mu-button type="submit" color="blue300">
                            <mu-icon value="create" left></mu-icon>新增
                        </mu-button>
                    </div>
                {% comment %} <button class="btn btn-outline-info" type="submit">create</button> {% endcomment %}
            </div>
        </form>
    </div>
</div>
{% endblock content %}

manager/templates/manager/edition_list.html
{% extends "manager/base.html" %}

{% block content %}
<div class="form">
    <h2>版型列表</h2>
    <table class="table">
        <tr>
            <th scope="col"></th>
            <th scope="col">版型</th>
            <th scope="col">價格</th>
        </tr>
        {% for edit in editions %}
            <tr>
                <th>{{ edit.id }}</th>
                <td><a href="{% url 'manager:edit-update' edit.id %}">{{ edit.edit_name }}</a></td>
                <td>{{ edit.charge }}</td>
            </tr>
        {% endfor %}
    </table>

    <div id="button" style="margin-left: 40%;">
        <mu-button color="teal900" href="{% url 'manager:manager-home' %}">
            <mu-icon value="arrow_back" left></mu-icon>返回
        </mu-button>
        <mu-button color="blue300" href="{% url 'manager:edit-create' %}">
            <mu-icon value="create" left></mu-icon>新增
        </mu-button>
    </div>
</div>

{% endblock content %}

manager/templates/manager/edition_update.html
{% extends "manager/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="form" id="button">
    <mu-button color="teal900" href="{% url 'manager:edit-list' %}">
        <mu-icon value="arrow_back" left></mu-icon>返回
    </mu-button></br></br>
    版型名稱：{{ object.edit_name }} </br>
    價格：{{ object.charge }}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>

            <div style="margin-left: 40%;">
                <mu-button type="submit" color="blue300" >
                    <mu-icon value="create" left></mu-icon>修改
                </mu-button>
            </div>
        </form>
</div>
{% endblock content %}

manager/templates/manager/home.html
{% extends "manager/base.html" %}

{% block content %}
<div class="form">
    <h2>付款情形</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">使用者</th>
                <th scope="col">標題</th>
                <th scope="col">上傳日期</th>
                <th scope="col">付款情形</th>
            </tr>
        </thead>
        <tbody>
            {% for pay in pays %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ pay.act_name.author.first_name }} ({{ pay.act_name.author }})</td>
                    <td><a href="{% url 'manager:postpay-detail' pay.id %}">{{ pay.act_name }}</a></td>
                    <td>{{ pay.act_name.date_post|date:"n-j , Y" }}</td>
                    <td>{% if pay.paid %}是{% else %}否{% endif %}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

manager/templates/manager/notpay_list.html
{% extends "manager/base.html" %}

{% block content %}
<div class="form">
    <h2>未付款列表</h2>

    <div id="button" >
        <mu-button color="teal900" href="{% url 'manager:manager-home' %}">
            <mu-icon value="arrow_back" left></mu-icon>返回
        </mu-button>
    </div>

    <table class="table">
        <thead>
            <tr>
            <th scope="col"></th>
            <th scope="col">使用者</th>
            <th scope="col">活動名稱</th>
            <th scope="col">付款情況</th>
            </tr>
        </thead>
        <tbody>
            {% for pay in pays %}
                {% if not pay.paid %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ pay.act_name.author.first_name }} ({{ pay.act_name.author }})</td>
                        <td><a href="{% url 'manager:postpay-detail' pay.id %}">{{ pay.act_name }}</a></td>
                        <td>{% if pay.paid %}是{% else %}否{% endif %}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

manager/templates/manager/post_detail.html
{% extends "manager/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div id="button" >
        <mu-button color="teal900" href="{% url 'manager:user-posts' user.username %}">
            <mu-icon value="arrow_back" left></mu-icon>返回
        </mu-button>
        <mu-button color="red" href="{% url 'manager:post-delete' object.id %}">
            <mu-icon value="delete" left></mu-icon>刪除
        </mu-button>
    </div>

    <article class="media content-section form">
        <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
            {% comment %} <a class="mr-2" href="#">{{ post.author.username }}</a> {% endcomment %}
                <a class="mr-2" href="{% url 'manager:user-posts' post.author.username %}">{{ post.author.username }}</a>
                <small class="text-muted">{{ object.date_post|date:"F d, Y" }}</small>
            </div>
            <div class="post_detail">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Update Post</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">submit</button>
                    </div>
                </form>
            </div>
        </div>
    </article>
{% endblock content %}

manager/templates/manager/post_list.html
{% extends "manager/base.html" %}

{% block content %}
<div class="form">
    <h2>Post列表</h2>
    <div id="button">
        <mu-button color="teal900" href="{% url 'manager:manager-home' %}">
            <mu-icon value="arrow_back" left></mu-icon>返回
        </mu-button>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">使用者</th>
                <th scope="col">活動名稱</th>
                <th scope="col">細項</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ post.author.username }}</td>
                    <td>{{ post.title }}</td>
                    <td><a href="{% url 'manager:post-detail' post.id %}">click me</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

manager/templates/manager/postpay_detail.html
{% extends "manager/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div id="button">
    <article class="media content-section">
        <div class="media-body">
            <div class="post_detail">
                <br />
                <mu-button color="teal900" href="{% url 'manager:post-list' %}">
                    <mu-icon value="arrow_back" left></mu-icon>返回
                </mu-button>
                <mu-button color="red" href="{% url 'manager:postpay-delete' object.id %}">
                    <mu-icon value="delete" left></mu-icon>刪除
                </mu-button>
                <br /><br />
                <h2>付款明細</h2>
                活動名稱：{{ object.act_name }} <br />
                版型：{{ object.edition }} <br />
                價格：{{ object.edition.charge }} <br />
                是否繳費：{% if object.paid %}是
                {% else %}
                    否
                    <div>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                {{ form|crispy }}
                            </fieldset>
                            <div class="form-group" style="margin-left: 40%;">
                                <mu-button type="submit" color="blue300" >
                                    <mu-icon value="create" left></mu-icon>修改
                                </mu-button>
                            </div>
                        </form>
                    </div>
                {% endif %}
                <br>
            </div>
        </div>
    </article>
</div>
{% endblock content %}

manager/templates/manager/user_detail.html
{% extends "manager/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div id="button" >
    <mu-button color="teal900" href="{% url 'manager:user-list' %}">
        <mu-icon value="arrow_back" left></mu-icon>返回
    </mu-button>
    <article class="media content-section form">
        <div class="media-body">
            <img class="rounded-circle article-img" src="{{ object.profile.image.url }}">
            <p class="article-content">
                帳號：{{ object.username }}
                使用者名稱：{{ object.first_name }}
                E-mail：{{ object.email }}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form|crispy }}
                    </fieldset>
                    {% comment %} <div class="form-group">
                        <button class="btn btn-info" type="submit">update</button>
                    </div> {% endcomment %}
                    <div style="margin-left: 40%;">
                        <mu-button type="submit" color="blue300" >
                            <mu-icon value="create" left></mu-icon>修改
                        </mu-button>
                    </div>
                </form>
            </p>
        </div>
    </article>
</div>
{% endblock content %}

manager/templates/manager/user_list.html
{% extends "manager/base.html" %}

{% block content %}
<div class="form">
    <h2>User List</h2>
    <div id="button" >
        <mu-button color="teal900" href="{% url 'manager:manager-home' %}">
            <mu-icon value="arrow_back" left></mu-icon>返回
        </mu-button>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">User</th>
                <th scope="col">User Name</th>
                <th scope="col"> </th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td><a href="{% url 'manager:user-posts' user.username %}">{{ user.username }}</a></td>
                    <td>{{ user.first_name }}</td>
                    <td><a href="{% url 'manager:user-detail' user.id %}">Update</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

manager/templates/manager/user_posts.html
{% extends "manager/base.html" %}
{% block content %}
    <div class="form">
        <div>
            <h1 class="mb-3">
                {% for post in posts|slice:":1" %}
                    {{ post.author }}
                {% endfor %}
                ({{ page_obj.paginator.count }})
            </h1>
        </div>
        <div id="button" >
            <mu-button color="teal900" href="{% url 'manager:user-list' %}">
                <mu-icon value="arrow_back" left></mu-icon>返回
            </mu-button>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">活動名稱</th>
                    <th scope="col">版型</th>
                    <th scope="col">金額</th>
                    <th scope="col">上架日期</th>
                </tr>
            </thead>
            {% for post in posts %}
                <tr>
                <th>{{ forloop.counter }}</th>
                <td><a href="{% url 'manager:post-detail' post.id %}">{{ post.title }}</a></td>
                <td>{{ post.edition }}</td>
                <td>{{ post.edition.charge }}</td>
                <td>{{ post.date_post|date:"n/j , Y" }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}