account/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import (
    PostListView, 
    PostDetailView, 
    PostCreateView, 
    PostUpdateView, 
    PostDeleteView,
    UserPostListView,
    PaymentListView,
    CustomizedCreateView,
    CustomizedDetailView,
    CustomizedListView
    )
from account import views as user_views

urlpatterns = [
    path('user_home/', PostListView.as_view(), name='user-home'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('payments/', PaymentListView.as_view(), name='user-payments'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('profile/', user_views.profile, name='profile'),
    path('choose/', user_views.choose_edition, name='choose'),
    path('customized_create/', CustomizedCreateView.as_view(), name='customized-create'),
    path('customized/<int:pk>/', CustomizedDetailView.as_view(), name='customized-detail'),
    path('customized/', CustomizedListView.as_view(), name='customized-list'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='index'),
    path('stream', views.stream, name='stream'),
]

manager/urls.py
from django.urls import path
from . import views
from manager.views import (
    PostpayListView, 
    EditionListView,
    PostpayUpdateView,
    EditionCreateView,
    EditionUpdateView,
    PostnotpayListView,
    PostListView,
    UserListView,
    UserUpdateView,
    UserPostListView,
    PostUpdateView,
    CustomListView,
    CustomUpdateView
)
from account.views import PostDeleteView, PostPayDeleteView

urlpatterns = [
    path('manager_home',PostpayListView.as_view(), name='manager-home'),
    path('postpay/<int:pk>/',PostpayUpdateView.as_view(),name='postpay-detail'),
    path('edition/create',EditionCreateView.as_view(), name='edit-create'),
    path('edition/',EditionListView.as_view(), name='edit-list'),
    path('edition/update/<int:pk>/',EditionUpdateView.as_view(), name='edit-update'),
    path('postpay/notpay',PostnotpayListView.as_view(), name='notpay-list'),
    path('post',PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostUpdateView.as_view(), name='post-detail'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('postpay/<int:pk>/delete',
         PostPayDeleteView.as_view(), name='postpay-delete'),
    path('user_list',UserListView.as_view(), name='user-list'),
    path('user_detail/<int:pk>/',UserUpdateView.as_view(), name='user-detail'),
    path('user_post/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('custom',CustomListView.as_view(), name='custom-list'),
    path('custom/<int:pk>/',CustomUpdateView.as_view(),name='custom-update'),
]

sign/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from sign import view
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include(('home.urls', 'home'), namespace='home')),
    path('user/', include(('account.urls', 'account'), namespace='account')),
    path('manager/', include(('manager.urls', 'manager'), namespace='manager')),
    path('register/', view.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
] + static(settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from account.models import Post

# Create your views here.


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'index.html', context)

def stream(request):
    return render(request, 'live_streaming.html')

templates/base.html
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% if title %}
        <title>{{ user.username }}-{{ title }}</title>
    {% else %}
        <title>Index</title>
    {% endif %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'account/main.css' %}">
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'account:user-home' %}">首頁</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'logout' %}">登出</a>
                {% if request.user.is_superuser  %}
                  <a class="nav-item nav-link" href="{% url 'register' %}">註冊</a>
                {% endif %}
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">登入</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="container">
        <div>
          {% if messages %}
            {% for messages in messages %}
              <div class="alert alert-{{ messages.tags }}">
                {{ messages }}
              </div>
            {% endfor %}
          {% endif %}
        </div>
        <div class="row">
          <div class="col-md-12">
            {% block content %}
            {% endblock content%}
          </div>
        </div>
      </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}
    home
{% endblock title %}
{% block content %}
    {% if user.is_authenticated %}
        {% if user.is_superuser %}
            <a class="btn btn-danger" href="{% url 'manager:manager-home' %}">manager</a>
        {% endif %}
        <a class="btn btn-dark" href="{% url 'account:user-home' %}">user</a>
    {% else %}
        <a type="button" class="btn btn-info" href="#">申請帳號</a>
    {% endif %}
{% endblock content %}

templates/login.html
{% extends "base.html" %}
{% block title %}
    登入
{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section form">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
        <legend class="border-bottom mb-4">登入</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">登入</button>
        </div>
    </form>
</button>
{% endblock content %}

templates/logout.html
{% extends "base.html" %}
{% block title %}
    登出
{% endblock title %}
{% block content %}
<div class="form">
    <h2>您已經登出了</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a class="ml-2" href="{% url 'login' %}">再次登入</a>
        </small>
    </div>
</div>
{% endblock content %}

templates/register.html
{% extends "manager/base.html" %}
{% block title %}
    login
{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
    {% if request.user.is_superuser  %}
        <div class="content-section">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Sign Up</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-info" type="submit">sign up</button>
                </div>
            </form>
        </button>
    {% endif %}
{% endblock content %}